{\rtf1\ansi\ansicpg1252\cocoartf2822
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 HelveticaNeue;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0\c10196;\cssrgb\c0\c0\c0;}
\margl1440\margr1440\vieww16600\viewh17380\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs38\fsmilli19200 \cf0 \cb2 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec3 site_name: D&D Compendium\
site_url: https://yourusername.github.io/dnd-compendum\
site_author: Sam Sturtevant\
site_description: D&D Compendium}